export enum SocketChannel {
    QUIT_ROOM = "QUIT_ROOM",
    PEER_QUIT_ROOM = "PEER_QUIT_ROOM",
    JOIN_ROOM = "JOIN_ROOM",
    GET_CURRENT_ROOM = "GET_CURRENT_ROOM",
    REQUEST_PEER_CONNECTION = "REQUEST_PEER_CONNECTION",
    PEER_CONNECTION_REQUESTED = "PEER_CONNECTION_REQUESTED",
    ACCEPT_PEER_CONNECTION_REQUEST = "ACCEPT_PEER_CONNECTION_REQUEST",
    PEER_CONNECTION_REQUEST_ACCEPTED = "PEER_CONNECTION_REQUEST_ACCEPTED",
    RECEIVE_CHATTING = "RECEIVE_CHATTING",
    EXILED = "EXILED",
    HALT_AUDIO = "HALT_AUDIO",
    RESUME_AUDIO = "RESUME_AUDIO",
    ENTER_LOUNGE = "ENTER_LOUNGE",
    PEER_ENTER_LOUNGE = "PEER_ENTER_LOUNGE",
    COME_BACK_ROOM = "COME_BACK_ROOM",
    PEER_COME_BACK_ROOM = "PEER_COME_BACK_ROOM",
}

export enum PeerChannel {}
