export enum Channel {
    QUIT_ROOM = "QUIT_ROOM",
    PEER_QUIT_ROOM = "PEER_QUIT_ROOM",
    JOIN_ROOM = "JOIN_ROOM",
    GET_CURRENT_ROOM = "GET_CURRENT_ROOM",
    REQUEST_PEER_CONNECTION = "REQUEST_PEER_CONNECTION",
    PEER_CONNECTION_REQUESTED = "PEER_CONNECTION_REQUESTED",
    ACCEPT_PEER_CONNECTION_REQUEST = "ACCEPT_PEER_CONNECTION_REQUEST",
    PEER_CONNECTION_REQUEST_ACCEPTED = "PEER_CONNECTION_REQUEST_ACCEPTED",
    RECEIVE_CHATTING = "RECEIVE_CHATTING",
    EXILED = "EXILED",
}
