export default {
    mainBlue: "#1d74ff",
    mainDarkBlue: "#004884",
    headerGray: "#c0d1ff",
    placeholder: "#8FBDFF",
    mailPlaceholder: "#ADADAD",
    buttonBlue: "#78B5FF",
    backgroundWhite: "#fafafa",
    loginMessageGray: "#C4C4C4",
    loginButtonYellow: "#AD882E",
    entryMainBlue: "#3653FF",
    entryLightBlue: "#9AA9FF",
    customRoomModalLightBlue: "#547FDD",
    customRoomModalInputBoxBlue: "#B7C8ED",
    mainPageGradient: "linear-gradient(50deg, #0058d8, #1d74ff, #0058d8)",
    blueGradient: "linear-gradient(50deg, #1A4CD2, #282D99)",
    orangeGradient: "linear-gradient(50deg, #F7931E, #F15A24)",
    animationCubic: "cubic-bezier(0.075, 0.82, 0.165, 1)",
    headerHeight: "160px",
    iconFont: "RecipeKorea",
    subLabelFont: "JejuGothic",
    plainTextFont: "NexonGothicLv1",
    plainLightTextFont: "NexonGothicLv1Light",
    plainBoldTextFont: "NexonGothicLv1Bold",
    inButtonFont: "SamlipHopang",
};
